name: Despliegue

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy to Develop environment
        run: |
          echo "Desplegando aplicación"
