name: CI

on:
  push:
  workflow_dispatch:

jobs:
  
  Build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Compilacion
        run: |
          #mvn package
          echo "build"
      - name: Ejecucion Test Unitarios
        run: |
          #mvn package test
          echo "Unit test"
  
  SCA:
    needs: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: SCA Analysis
        run: |
          echo "SCA"
  
  SAST:
    needs: Build
    runs-on: ubuntu-latest
    steps:   
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Analisis SonarCloud
        run: |
          echo "SAST"
          
  Docker-build:
    needs: 
    - SAST
    - SCA
    runs-on: ubuntu-latest
    steps:
    
      - name: Docker Login
        run: |
          echo "Docker login"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Docker build
        run: | 
          #docker build -t clagosu/ms-aumento-voto:latest .
          echo "Docker build"

  Image-Vulnerability-Analysis:
    needs: Docker-build
    runs-on: ubuntu-latest
    steps:
    
      - name: Image Analysis
        run: |
          echo "Image Analysis"

  Docker-push:
    needs: 
      - Image-Vulnerability-Analysis
    runs-on: ubuntu-latest

    steps:
    
      - name: Docker push
        run: |
          echo "Docker push"
  
  Deploy:
    needs: Docker-push
    runs-on: ubuntu-latest
    steps:

      - name: Clonacion de codigo
        uses: actions/checkout@v4
      
      - name: Despliegue
        run: |
          echo "Despliegue"
          #kubectl apply -f deploy.yaml
          
  DAST:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Clonacion de codigo
        uses: actions/checkout@v4
      - name: Despliegue
        run: |
          echo "Despliegue"
          #kubectl apply -f deploy.yaml
